### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by guyluz11** [xuegao-tzx/whisper_flutter_new#11]
Let's add Linux support.

When trying to run it I get some simple error, maybe the change is not so big.

```dart
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ ⛔ Error initializing Whisper: UnimplementedError: getLibraryPath() has not been implemented.
flutter: │ ⛔ #0      PathProviderPlatform.getLibraryPath (package:path_provider_platform_interface/path_provider_platform_interface.dart:55:5)
flutter: │ ⛔ #1      getLibraryDirectory (package:path_provider/path_provider.dart:100:40)
flutter: │ ⛔ #2      Whisper._getModelDir (package:whisper_flutter_new/whisper_flutter_new.dart:55:17)
flutter: │ ⛔ #3      Whisper._initModel (package:whisper_flutter_new/whisper_flutter_new.dart:60:35)
flutter: │ ⛔ #4      Whisper._request (package:whisper_flutter_new/whisper_flutter_new.dart:78:13)
flutter: │ ⛔ #5      Whisper.getVersion (package:whisper_flutter_new/whisper_flutter_new.dart:126:47)
flutter: │ ⛔ #6      _AudioTranscribeRepository.initWhisper (package:map_tube/infrastructure/audio_transcribe_repository.dart:59:38)
flutter: │ ⛔ <asynchronous suspension>
flutter: │ ⛔ #7      _AudioTranscribeRepository.waitForInitialization (package:map_tube/infrastructure/audio_transcribe_repository.dart:128:5)
flutter: │ ⛔ <asynchronous suspension>
flutter: │ ⛔ #8      _InitializingAppPageState.manageSetUp (package:map_tube/presentation/pages/initializing_app_page.dart:70:5)
flutter: │ ⛔ <asynchronous suspension>
flutter: │ ⛔ 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by xuegao-tzx** [comment]
Support for Linux and Windows may be more complicated than expected, mainly because I have no experience in PC development
